version: 2.1
orbs:
  node: circleci/node@5
     
deploy:
    # This is an example deploy job, not actually used by the workflow
    mysql:
      image: mysql:8.0.33
    front:
      image: nginx:latest
    steps:
      # Replace this with steps to deploy to users
      - run:
          name: deploy
          command: docker-compose build / docker-compose up

         
