#COPY ./default.conf /etc/nginx/conf.d/default.conf
# Use a base image with NodeJS 18
FROM node:18
RUN rm -rf /www
WORKDIR /www
COPY back/ /www

RUN npm install

# Expose the application port
EXPOSE 3000
EXPOSE 447
# Run the App
CMD npm start

